name: live_tracker_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.9.0
  flutter_polyline_points: ^2.1.0
  # location: ^4.4.0
  flutter_svg: ^2.0.10
  location: ^6.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/icons/
